import Head from 'next/head';
import { useEffect } from 'react';
import { Aircraft } from '../components/Aircraft';
import { Cloud } from '../components/Cloud';
import Flybird from '../components/Flybird';
import Parachute from '../components/Parachute';
import Star from '../components/Star';

export default function Home() {
  const aircraft = new Aircraft(1024 / 8, 768 / 2);
  let intervalGame;
  let canvas;
  let ctx;
  let lastBirdSpawnAt = Date.now();
  let lastCloudSpawnAt = Date.now();
  let lastParaSpawnAt = Date.now();
  let lastStarSpawnAt = Date.now();
  let isStart = false;

  const randomNumber = (min, max) => Math.random() * max + min;
  const birds = [];
  const clouds = [];
  const parachutes = [];
  const stars = [];

  setInterval(() => {
    if (aircraft.fuel > 0) {
      aircraft.decreaseFuel();
      aircraft.increaseTime();
    }
  }, 1000);

  function clearIntervalGame() {
    clearInterval(intervalGame);
    intervalGame = null;
  }

  function startGame() {
    canvas = document.getElementById('myCanvas');
    if (!intervalGame) {
      intervalGame = setInterval(() => {
        ctx = canvas.getContext('2d');
        ctx.clearRect(0, 0, 1024, 768);

        const random = randomNumber(100, 700);
        if (Date.now() - lastBirdSpawnAt > 1000) {
          const newBird = Flybird(1026, random);
          birds.push(newBird);
          lastBirdSpawnAt = Date.now();
        }

        const randomClouds = randomNumber(-50, 700);
        if (Date.now() - lastCloudSpawnAt > 1000) {
          const newCloud = new Cloud(1060, randomClouds);
          clouds.push(newCloud);
          lastCloudSpawnAt = Date.now();
        }

        const randomParahcure = randomNumber(0, 1000);
        if (Date.now() - lastParaSpawnAt > 3500) {
          const newPara = Parachute(randomParahcure, -50);
          parachutes.push(newPara);
          lastParaSpawnAt = Date.now();
        }

        const randomStar = randomNumber(0, 1000);
        if (Date.now() - lastStarSpawnAt > 2500) {
          const newStar = Star(randomStar, -50);
          stars.push(newStar);
          lastStarSpawnAt = Date.now();
        }

        clouds
          .filter((cloud) => !cloud.isDespawn())
          .forEach((cl) => {
            cl.update();
            cl.draw(ctx);
          });

        parachutes
          .filter((pr) => !pr.isDead())
          .forEach((prct) => {
            prct.update(aircraft);
            prct.draw(ctx);
          });

        stars
          .filter((st) => !st.isDead())
          .forEach((str) => {
            str.update(aircraft);
            str.draw(ctx);
          });

        birds
          .filter((enemy) => !enemy.isDead())
          .forEach((bird) => {
            bird.update(aircraft);
            bird.draw(ctx);
          });

        aircraft.update();
        aircraft.draw(ctx);

        if (aircraft.ending) {
          clearIntervalGame();
        }
      }, 1000 / 30);
    }
  }

  function handleKeydown(e) {
    if (e.keyCode === 32) {
      if (aircraft.ending) return;
      if (isStart) {
        clearIntervalGame();
      } else {
        startGame();
      }
      isStart = !isStart;
    }
  }

  useEffect(() => {
    window.addEventListener('keydown', handleKeydown);

    return () => {
      window.removeEventListener('keydown', handleKeydown);
      document.exitFullscreen();
    };
  }, []);

  return (
    <div className="w-full h-screen">
      <Head>
        <title>Sky Angel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full h-full flex flex-row items-center justify-center">
        <canvas
          id="myCanvas"
          width="1024"
          height="768"
          className="border border-black bg-[#BFEAF5]"
        />
      </div>
    </div>
  );
}
