import Head from 'next/head';
import { useEffect, useState } from 'react';
import { Aircraft } from '../components/Aircraft';
import { Cloud } from '../components/Cloud';
import Flybird from '../components/Flybird';
import Parachute from '../components/Parachute';

export default function Home() {
  const [start, setStart] = useState(false);
  const aircraft = new Aircraft(1024 / 8, 768 / 2);
  let canvas;
  let ctx;
  let lastBirdSpawnAt = Date.now();
  let lastCloudSpawnAt = Date.now();
  let lastParaSpawnAt = Date.now();

  const randomNumber = (min, max) => Math.random() * max + min;
  let birds = [];
  const clouds = [];
  const parachutes = [];

  setInterval(() => {
    if (aircraft.fuel > 0) {
      aircraft.decreaseFuel();
    }
  }, 1000);

  useEffect(() => {
    document.onkeydown = (e) => {
      if (e.keyCode === 32) {
        setStart(!start);
      }
    };
  }, [start]);

  useEffect(() => {
    canvas = document.getElementById('myCanvas');
    // if (document) {
    // document.onkeydown = (e) => {
    //   console.log('document.onkeydown', e.keyCode);
    //   if (e.keyCode === 32) {
    //     setStart(!start);
    //   }
    // };
    // }

    if (!aircraft.ending) {
      setInterval(() => {
        if (!start) return;
        ctx = canvas.getContext('2d');
        ctx.clearRect(0, 0, 1024, 768);
        aircraft.update();
        aircraft.draw(ctx);

        const random = randomNumber(100, 700);
        if (Date.now() - lastBirdSpawnAt > 1000) {
          const newBird = Flybird(1026, random);
          birds.push(newBird);
          lastBirdSpawnAt = Date.now();
        }
        const randomClouds = randomNumber(-50, 700);
        if (Date.now() - lastCloudSpawnAt > 1000) {
          const newCloud = new Cloud(1060, randomClouds);
          clouds.push(newCloud);
          lastCloudSpawnAt = Date.now();
        }

        const randomParahcure = randomNumber(0, 500);
        if (Date.now() - lastParaSpawnAt > 5000) {
          const newPara = Parachute(randomParahcure, -10);
          parachutes.push(newPara);
          lastParaSpawnAt = Date.now();
        }

        clouds
          .filter((cloud) => !cloud.isDespawn())
          .forEach((cl) => {
            cl.update();
            cl.draw(ctx);
          });

        parachutes
          .filter((pr) => !pr.isDead())
          .forEach((prct) => {
            prct.update(aircraft);
            prct.draw(ctx);
          });

        birds
          .filter((enemy) => !enemy.isDead())
          .forEach((bird) => {
            bird.update(aircraft);
            bird.draw(ctx);
          });

        if (aircraft.ending) {
          birds = [];
        }
      }, 1000 / 30);
    }
  });
  return (
    <div className="w-full h-screen">
      <Head>
        <title>Sky Angel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full h-full flex flex-row items-center justify-center">
        <canvas
          id="myCanvas"
          width="1024"
          height="768"
          className="border border-black bg-[#BFEAF5]"
        />
      </div>
    </div>
  );
}
